

# docker-compose -f docker-compose.dev.yml up --build
# run containers with tests and db

version: '2.1'
services:
  mysql:
    image: mysql:5.6
    restart: always
    command: --max_allowed_packet=32505856 
    healthcheck:
      test: "exit 0"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test 

  web:
    build: .
    ports:
      - 8081:8081
    depends_on:
        mysql:
          condition: service_healthy  
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:    
      - DATABASE_HOST=mysql